# Generated by Django 3.2.6 on 2021-08-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
