# Generated by Django 3.2.6 on 2021-08-15 14:20

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_polygon_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='polygon_area',
            field=djgeojson.fields.PolygonField(),
        ),
    ]
